### GET /
GET http://localhost:5000

### REGISTER user 
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username" : "abc",
    "password" : "abc"
}

###LOGIN user
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username" : "abcd",
    "password" : "abcd"
}