### GET /
GET http://localhost:5000

### REGISTER user 
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username" : "abc123",
    "password" : "abc123"
}

###LOGIN user
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username" : "abc123",
    "password" : "abce123"
}